# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# This workflow will install genezio, then run genezio deploy for your project.
#
# Note: Set a genezio action token in Github Actions secrets name `GENEZIO_TOKEN`:
#
# See the documentation for more details and best practices.
# https://docs.genez.io/genezio-documentation/integrations/github-action

name: Deploy project with genezio
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      # Install genezio and authenticate with the genezio access token
      - uses: Genez-io/genezio-github-action@main
        with:
          genezio-version: latest
          token: ${{ secrets.GENEZIO_TOKEN }}
      - name: Deploy the backend with genezio
        working-directory: ./server
        run: genezio deploy --backend
      - name: Deploy the frontend with genezio
        working-directory: ./server
        run: genezio deploy --frontend
